services:
  netbird-peer:
    container_name: hostname
    hostname: hostname
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    devices:
      - /dev/net/tun
    network_mode: host
    environment:
      - NB_MANAGEMENT_URL=<URL>
      - NB_SETUP_KEY=<SETUP KEY>
    volumes:
      - /home/X27/docker/netbird/data:/var/lib/netbird
    image: netbirdio/netbird:latest
    restart: unless-stopped
