services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
    volumes:
      - ./config:/config
    ports:
      - 8080:8080
    restart: unless-stopped
